In [36]:
import numpy as np

array = np.array([1,2,3,4,5,6])


In [37]:
array

array([1, 2, 3, 4, 5, 6])

In [38]:
type[array]

type[array([1, 2, 3, 4, 5, 6])]

In [39]:
array.shape

(6,)

In [40]:
#更换数组的纬度
array.shape = (2,3)

In [41]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
#修改成原本的纬度

array.shape = (6,)
array

array([1, 2, 3, 4, 5, 6])

In [43]:

array += 1
array
array *=2
array

array([ 4,  6,  8, 10, 12, 14])

In [44]:
array > 3

array([ True,  True,  True,  True,  True,  True])

In [45]:
array

array([ 4,  6,  8, 10, 12, 14])