In [24]:
import numpy as np
a = np.array([1,2,3,4,5,6])

# create array by range
b = np.arange(1,10,2)

# create all zeros
c = np.zeros(10,dtype="int32")

#create all one
d = np.ones((2,3),dtype='float32')

In [25]:
a
b
c
d

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [26]:
a

array([1, 2, 3, 4, 5, 6])

In [27]:
b

array([1, 3, 5, 7, 9])

In [28]:
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [29]:
d

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [30]:
d[1]

array([1., 1., 1.], dtype=float32)

In [31]:
d[1][1]

1.0

In [32]:
# This function is to create an all element zero array which is same with a
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0])

In [34]:
# This function is to create an all elements are 1 array which is same with a
np.ones_like(a)

array([1, 1, 1, 1, 1, 1])

In [35]:
# object property

In [36]:
"""
1- Sharp : 显示数组的纬度
2- dtype : 显示数组的数据类型
3- 或者可以调用astype 把当前的数据类型转换成其他的数据类型
4- 使用size 查看数组内数据的数量
"""

a.shape

(6,)

In [37]:
a.dtype

dtype('int64')

In [38]:
a.astype(float)

array([1., 2., 3., 4., 5., 6.])

In [39]:
x = a.astype(float)

In [40]:
x.dtype

dtype('float64')

In [41]:
a.size

6

In [45]:
d = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6]
])
d.shape

(2, 5)

In [46]:
d.size

10

In [47]:
e = d *2

In [48]:
e

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12]])

In [49]:
e.shape

(2, 5)

In [50]:
e.shape = (5,2)

In [53]:
e

array([[ 2,  4],
       [ 6,  8],
       [10,  4],
       [ 6,  8],
       [10, 12]])

In [55]:
# 返回最外层数组的元素数量
len(e)

5

In [57]:

f = np.arange(1,19)

In [58]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [63]:
#三页 , 每一页具有三行两列
f.shape = (3,3,2)

In [60]:
f

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [61]:
f.size

18

In [62]:
len(f)

3

In [65]:
# 元素访问, 页 行 列
f[0][0][1]

2

In [66]:
#和上面的一模一样
f[0,1,0]

3

In [68]:
for i in range(1,10) :
    print(i)

1
2
3
4
5
6
7
8
9


In [77]:
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for x in range(f.shape[2]):
            print(f[i,j,x])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [78]:
f

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])