In [3]:
import numpy as np

a = np.arange(1,9)

print(a)

[1 2 3 4 5 6 7 8]


In [5]:
b = a.reshape(2,4)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
c = a.reshape(2,2,2)

In [8]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
c[0,0,0]

1

In [11]:
c[0,0,0]=2

In [12]:
a[0]

2

In [14]:
#注意,这个reshape修改后的数据纬度里面的数据是共享的, 修改A之后,B也被修改了
# 可以把多位数组修改成一维数组,原始数组和修改后的数组是独立的

d = c.flatten()
d

array([2, 2, 3, 4, 5, 6, 7, 8])

In [15]:
d[0]=3

In [16]:
d

array([3, 2, 3, 4, 5, 6, 7, 8])

In [17]:
c

array([[[2, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
#不独立的伸平
c.ravel()

array([2, 2, 3, 4, 5, 6, 7, 8])

In [19]:
e=c.ravel()

In [20]:
e

array([2, 2, 3, 4, 5, 6, 7, 8])

In [21]:
e[0]=9

In [22]:
c

array([[[9, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])