In [29]:
import numpy as np


arr = np.arange(1,10)


arr[0:9:1]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr[::2]

array([1, 3, 5, 7, 9])

In [3]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [5]:
arr[-7::-2]

array([3, 1])

In [6]:
arr[2::3]


array([3, 6, 9])

In [9]:
arr[:-9:-3]

array([9, 6, 3])

In [31]:
# 二维数组切片
arr.resize(3,3)

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr[2,]

array([7, 8, 9])

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# 第二行 第二列
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [38]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [39]:
arr[::2,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [40]:
arr[::2,::2]

array([[1, 3],
       [7, 9]])

In [42]:
arr[::,0]

array([1, 4, 7])

In [43]:
#测试Mask operation


"""
掩码操作 只有true 和 false . 使用mask logincal and with the original data set . then got the result
"""

a = np.arange(1, 100)

mask = (a % 3 == 0)

a[mask]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [44]:

# 基于索引的Mask

names = np.array(["apple", "banana", "juice", "fruit", 'flower'])

index = [0,2,3,1,4]

names[index]

array(['apple', 'juice', 'fruit', 'banana', 'flower'], dtype='<U6')