In [1]:
import numpy as np
# 数组的拆分和组合 水平， 垂直 深度（深度组合类似直接堆叠在一起） 成三维的

array = np.arange(1,19)

array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [3]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [7]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.vstack((arr1,arr2))


In [8]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
a,b,c,d= np.vsplit(arr3,4)

In [11]:
a

array([[1, 2, 3]])

In [12]:
b

array([[4, 5, 6]])

In [13]:
c

array([[7, 8, 9]])

In [14]:
d

array([[10, 11, 12]])

In [15]:
arr4 = np.hstack((a,b,c,d))

In [16]:
arr4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

ValueError: cannot reshape array of size 6 into shape (1,)

In [24]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [23]:
#深度堆叠
arr3 = np.dstack((arr1, arr2))
arr3

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [29]:
# 可以先输出原本堆叠的数组，堆叠后的数组和堆叠前的数组下面对应相等

arr4,arr5 = np.dsplit(arr3,2)

In [30]:
arr4

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [31]:
arr5

array([[[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [33]:
arr6 = np.dstack((arr4,arr5))
arr6

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

AttributeError: 'numpy.ndarray' object has no attribute 'reshap'