In [15]:
import numpy as np

a = np.arange(1,9)

b = np.arange(1,20)

In [16]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [18]:
"""
数据补全功能
pad-width (x,y) x 从头部开始
y: 从尾部开始
补全的模式为 常量
补全的值
"""
a = np.pad(a, pad_width=(0,11), mode="constant", constant_values=0);


In [19]:
c = a+b

In [20]:
c

array([ 2,  4,  6,  8, 10, 12, 14, 16,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
"""
一位数组的组合方式
水平或者垂直
"""

d = np.arange(1,10);
e = np.arange(10,19)


In [22]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
e

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [25]:
# 行组合, 两行组合在一起
f = np.row_stack((d,e))

In [26]:
f

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [27]:
#列组合, 两列组合在一起
g = np.column_stack((d,e))
g

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14],
       [ 6, 15],
       [ 7, 16],
       [ 8, 17],
       [ 9, 18]])

In [28]:
"""
数组的属性
shape 纬度
size 数量
ndim 纬数 len(shape)
item size 元素字节数
nbyte 总字节数 = size * itemSize
real 实数
imag 虚数
T 数组对象的转制试图
flat 扁平迭代器
"""

temp = np.arange(1,11)




In [40]:
temp = np.array([
    [1,2,32222322323234,5],
    [1,34,56,7]
])


In [38]:
temp.shape

(2, 4)

In [41]:
temp.size

8

In [32]:
temp.ndim

2

In [33]:
len(temp.shape)

2

In [34]:
temp.itemsize

8

In [42]:
temp.nbytes

64

In [43]:
temp.real

array([[             1,              2, 32222322323234,              5],
       [             1,             34,             56,              7]])

In [44]:
temp.imag

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
for i in temp.flat:
    print(i)

1
2
32222322323234
5
1
34
56
7
